spring:
  batch:
    job:
      enabled: false
      #??? ?? ? ??? ??? 1?? ?? ??? ??
      #????? ???? ???? ?? ??? ???? ??? ?? ??? ??? ??.
    jdbc:
      initialize-schema: always #similar with jpa ddl-aoto
      #schema: meata data location

  datasource-meta:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:??????;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  datasource-data:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:??????;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: